[mappings]

"111.src.piston.com" = [
  "222.snk.piston.com",
]

[connection]

peer_root = """
-----BEGIN CERTIFICATE-----
MIIBgTCCASagAwIBAgIUGwsLnjc5BIBysnSfTbHp1tD9IxAwCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTVG9wLWxldmVsIEVwdGhvcyBDQTAeFw0yNTA5MTcxMTA2NTRa
Fw0zNjEyMDQxMTA2NTRaMB4xHDAaBgNVBAMME1RvcC1sZXZlbCBFcHRob3MgQ0Ew
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASKFjQu4Myw6uXMcyz+9hKnLPG1Cny3
zY/nYg/llJqfyxy40PyC3BawfpvVMrKH4zuXpKUt/wtF/3UeoEZL2TY6o0IwQDAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU90cVLK8Q
ORkZtXZArtlZFcslMtUwCgYIKoZIzj0EAwIDSQAwRgIhANKNjiYbUeCtwR6F10iO
K5VTdRH6LR2f7GjP/MOHop3wAiEA3TOyd4jfebK+j7IfRZxnRbJWYRf51zYrXVL6
UNmIu0Y=
-----END CERTIFICATE-----
"""

certificate = """
-----BEGIN CERTIFICATE-----
MIIDUDCCAjigAwIBAgIUbmGrEzLYH2Nlen7DUvWl8AGZG8kwDQYJKoZIhvcNAQEL
BQAwITEfMB0GA1UEAwwWSW50ZXJtZWRpYXRlIEVwdGhvcyBDQTAeFw0yNTA5MTcx
MTA3MDNaFw0yNjA5MTcxMTA3MDNaMBwxGjAYBgNVBAMMEWJyb2tlci5lcHRob3Mu
bmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0MCk3eTo9fge3Vi8
m4b7VVdLqjyYOcCh6jT9clGdrBucF2hLAptzjSATWOMvzKEfepYbZogLPtyvSlFN
yPz3DHQ0CY0HCdwCUZmsTiJSyufdCHj6o0wT//D+jWue0MIwdlF/0IkGLF0SH128
4DsbbGURkrnAwkcxpTtMIthQVbmdGyGqJAtA5flPMsvfBeiaiM0suhO6PFsStJsk
4Uxjql+qA4bsMmQnqCgOc0iFKz/ThChqcRyOKfDhbd3+tiS35FAyXgYzpnQdN7uy
O4RycQd3+Y9cebAmclun4mOOPqrIoiJ3OkYFU458vz556LWDqGl86vccpT5mCkU9
xfGojQIDAQABo4GEMIGBMAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUH
AwEwHAYDVR0RBBUwE4IRYnJva2VyLmVwdGhvcy5uZXQwHQYDVR0OBBYEFALIbpGp
CB4c+tBEIYSbUaOe5SqlMB8GA1UdIwQYMBaAFEmAhiM+ExIGiud+UhGh/7nlsHCR
MA0GCSqGSIb3DQEBCwUAA4IBAQCgZ6dHVrgwNESZJZCWYMlflpeZT0w8N6zY4gie
9IEqjsL42ycfG20nlfqgk/hiSq22hS59XkDIEdFeCEE+QxagbzhdzqNTHntKdNXh
wBebWlzVJnPWvndPsTgT17y1ls7p+N/qGYO896Itht1OkjZoSrQMo9U9OWoVTZLg
vIgrkympaim9MwSmVUeWJ/nWMjf/iBLoqVYYew+zhQstUxPitcR88gFGJJC8mX9w
Mej1COVCaipntXCrXcND5M1aHl9HJAwayDjieunBbLibVDu/q5aQvCtv9aSGAPQa
bSmpoAsWz9hEg5lmYZ91tRclozC0+6hIrIypLM7azKG1lLK4
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICczCCAhigAwIBAgIUCzppOiQ/BoqHR0fOTRFrzpFULkMwCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTVG9wLWxldmVsIEVwdGhvcyBDQTAeFw0yNTA5MTcxMTA2NTRa
Fw0zNjEyMDQxMTA2NTRaMCExHzAdBgNVBAMMFkludGVybWVkaWF0ZSBFcHRob3Mg
Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3q7tc/CF3KKSnHrBd
MynML/zgU8+cCjy28xjLDFRlGmHQ6J7ZIUN8kVWdItMmZH81KRG015PB90aWEaJ6
j5oIvoeUDVGp6JMQjMgAV4yUbN/MMBpyI+2NFfp08fOXHF7wO9hTYH7DyK4hFrca
ZPvMvU+7U7/4CWyM+4wpj9Rsisqt9dHGLlz+HGcW0OdTzB62LGvtb06iUVCvY64g
X8L8dU4C3Ly6m+jzCbVq/mR4fc3BUYFBMGPofu7cYkvy7tUC5of9t0ogWLBklaUD
Dit16Y9r+VyRUZFc3NBffI6kubldpRitpTXrGyZkxgJVF2a33uHqmNPeIguE9WwW
rGZXAgMBAAGjZjBkMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/BAQDAgEG
MB0GA1UdDgQWBBRJgIYjPhMSBornflIRof+55bBwkTAfBgNVHSMEGDAWgBT3RxUs
rxA5GRm1dkCu2VkVyyUy1TAKBggqhkjOPQQDAgNJADBGAiEAoufClsEIhnv0zyaT
1LTAGAsZ175Xgd8PcVPGz0LSk5ECIQC0zwy6MexMn+2NVncRgnGtNp6m/a1/rMkm
PJvlJBgmjA==
-----END CERTIFICATE-----
"""

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQwKTd5Oj1+B7d
WLybhvtVV0uqPJg5wKHqNP1yUZ2sG5wXaEsCm3ONIBNY4y/MoR96lhtmiAs+3K9K
UU3I/PcMdDQJjQcJ3AJRmaxOIlLK590IePqjTBP/8P6Na57QwjB2UX/QiQYsXRIf
XbzgOxtsZRGSucDCRzGlO0wi2FBVuZ0bIaokC0Dl+U8yy98F6JqIzSy6E7o8WxK0
myThTGOqX6oDhuwyZCeoKA5zSIUrP9OEKGpxHI4p8OFt3f62JLfkUDJeBjOmdB03
u7I7hHJxB3f5j1x5sCZyW6fiY44+qsiiInc6RgVTjny/PnnotYOoaXzq9xylPmYK
RT3F8aiNAgMBAAECggEAMf4gvZ9Hhzh/s8S/joOaB0sbrM5MKnCOljdQhyMynngS
PqzUYfB2kNKgr4Xg+aGQl1wBfeGQx+Iz/JlSBpNGWu4tVCg5CkxtJbumvyOLLlqu
3YuTgq4CkCXX4GhopVgMIRnNgVR/bPpxD5/0TsL5A1GFDt17Y0uHgSmdRy8EtjKJ
sg6AANGmHG9QEnG5S/mSiZSV8wG1SjhCcX8VQDtCx5AiUwRcfg1/Q04VPqMjVSvD
wNvMG5qT3r1/2gFHHi0zaVwJVktQYVi7j75RVtIw6r+H2/diYmohfF23eTs6Tiyw
jWvnfTgsyNMKkbhamlgwgjk/1RhBbeBDqqmiu7V+QQKBgQDxBEdlIqosGLdrFjRB
H+2Iv5jEUIuDw2NjkewH0qfPVRnmanotT6qxY05wN5Bc1KFokb9WStpGiW8C87rs
oxHBWgkq7klsXDQS3RqYb0/Ooi8scyRkpUJmD8mb2fPIpTeymehmCWgqn14FIBjo
Ky5Nt5xVwO1vhD+nmaUsSmtBPQKBgQDduuNvcPOeqQ54gzD58iJvieZmfoN2Ip/0
ARMvZuBsjbnd+FwS3SVzlLPl9P0raoQ9beQ6DKwUv332CcTXIr5hnLvvNZg7IsJy
o2kezYjTKNuMG7Uxgi49BmkTmiF0UMSlKKESdgv3Geg4QfKG8orE1XwJr0vwZJvf
4OeeLMnZkQKBgFNgt5I1O8mlg054j/s3oGT+Y0sG0jzzCx8XDCBor8T6G8uqajni
pZpYUHphvn9ez7ftM9QWcQyV3uGWj8PtZecNzr4bUSs7eohMFTdGysUhNlCaRKzM
vvuv2n8gF0YCYhJXTB6Agpi8KTp8sCEhTxNzwZGo/HrntV21uX5pAFHBAoGAYmmw
yKW5e5JNee/ArS9rWVY7jQJaFvUHSaWwfjmLIqNE++Bf/X9qQAKgVlCGjd6ZEyrT
QXCecBcOMUXkuBgTp/+I6oM/LgAfjgI5hhJzyEU6LNWfdnnxS+SsfqbKcnXm0edW
lnsOlH5LM60RmBPOw859X08OxYPiK1wHcY0vigECgYBHLKj+uFTfPNUz/J0xMFPn
BmNYzply0w+4R1v7mp3l6NZMGjkawL9szuJNuQ4vEGqWdUbDVwmHZGvesTksllog
nJckV0fYXkVVlQfVtk9tbuEG2ya5OemrXze3Km/wm3U09VbvJbzKADRwqt8tog+H
hQvYB3jmfjXD1Y9j8vm+yA==
-----END PRIVATE KEY-----
"""

[server]
address = "[::0]:50001"

[process]
tracing_level = "INFO"
