[mappings]

"111.src.piston.com" = [
  "222.snk.piston.com",
]

[connection]

peer_root = """
-----BEGIN CERTIFICATE-----
MIIBgDCCASagAwIBAgIUVZ8Oc+7D9CQRKpVRF8WnVM04c+4wCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTVG9wLWxldmVsIFBpc3RvbiBDQTAeFw0yNDA0MTkwMTAwMDZa
Fw0yNTA0MTkwMTAwMDZaMB4xHDAaBgNVBAMME1RvcC1sZXZlbCBQaXN0b24gQ0Ew
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATB3LLc95dRzz8aPbO8K+IzgcmQdwWE
YUh3fjjvw5Tf7A8h6lT5DJzxCXlOkB+OgKkgIjTtpos3cKYapUIDvwO3o0IwQDAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUcGk4/Us6
HlU4xEz9G7fCYn7rccwwCgYIKoZIzj0EAwIDSAAwRQIgWPd6O5kWas1HEC1w5hKK
CL01NWY5f+azzi7rjR2UxCkCIQCKySwv3ry/JyvYtniOGW/uhKLiAgbcGj+0MWIe
KtmQTA==
-----END CERTIFICATE-----
"""

certificate = """
-----BEGIN CERTIFICATE-----
MIIDUDCCAjigAwIBAgIUDTICvjZiIdzarB38mCFn297uINcwDQYJKoZIhvcNAQEL
BQAwITEfMB0GA1UEAwwWSW50ZXJtZWRpYXRlIFBpc3RvbiBDQTAeFw0yNDA0MTkw
MTAwMTBaFw0yNTA0MTkwMTAwMTBaMBwxGjAYBgNVBAMMEWJyb2tlci5waXN0b24u
Y29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6+67QSraSg8lHWLS
HJEimfyrdCIjZ0UyK63T+qvL2e5fPTmYcaLp1jZkLE7RfAgFc/RyxkKzvHfTQnm0
B8nzLXYxYDCOXj4hboBuklyby6IOu8JOEM/IcbAUthg1UD+PdXgau/j84XqBOTYM
BSMJhONXspgDp3FgjNKQR/U/spfnh7LQxNw10D1kuUxLMpH5sOjfRQfHqzwUWnlK
yVv/ZKJ0zKuCoMxupOWoMxRFoFTZuNNh5b33lH8hpbJGzZTzKkxxDxnNM3xUc3/g
INmBS92pdpp01xfP8AoYipUy3XS+ukxS0mBuLxO0su76KzSktBXp4p+9pDxhMVyY
+xePHQIDAQABo4GEMIGBMAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUH
AwEwHAYDVR0RBBUwE4IRYnJva2VyLnBpc3Rvbi5jb20wHQYDVR0OBBYEFNNoz0bI
rI7qC72MRfr13HcNxn64MB8GA1UdIwQYMBaAFG1W3v8AOh0OmPHgRynMwEtpCcSe
MA0GCSqGSIb3DQEBCwUAA4IBAQBNSJn/doBd6Xou8LPETDsRYsofR+BwoH9Eh5jN
3pIarckeaTRSPRlwdqr6jB5zq7zV8p7DFPVo0v2p839jCRLX6vkYPnPPvd/lZVvp
6TzU+t6HOvDEvM7j2N85d+t8KeFSfzJRcddT2e31UTR6wJTWRhAD4shybmvSPX02
n+etO2pDmBXFOBKK31G3X9QT+kgQZrrpFYx+770rQ9N39s96VjBAzoC4HOvhtYU8
7vHyfbcULcFHj2wSW7AUyHuOb0hOiuN1HGUWaIBt4ws4EAcRUr3Fwr9n16UUEnHC
zXfmFkwuLt/KhWayw2ftUbnCdBux29zKyImtF2/mkFh310p8
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICcjCCAhigAwIBAgIUd/k1v58AD5O6eClCVUpwUHzNZPAwCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTVG9wLWxldmVsIFBpc3RvbiBDQTAeFw0yNDA0MTkwMTAwMDda
Fw0yNTA0MTkwMTAwMDdaMCExHzAdBgNVBAMMFkludGVybWVkaWF0ZSBQaXN0b24g
Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDc4vHlq2eiZrDrSwjx
Q8A2iUa7DRYc87pmgXH3wMvBqcPYItn5D+zOSf7cJVV5o+MnjXA5KjTQzCMVwL2y
5RCw10NPHwdwwD56UaRxq8uOpdTjkq1qIhEWnguRe0CU5TqpbYUtUO0w48AL02j6
1E1V7WDLzYwrHZpMD7uhx/IpEXBQSi7JHycekbR6A5heyV5UV+uyZ0ecMqFNsZtG
si4Q8oCjVfeKHsO3kcknCliG2X5CnzCV6XbE+xWtXJIfJK4sRF/NOgFZKgg6bmur
Q6aFEKovVKnk1XNyiIHprUnMaBgaBnVycMOBvK6pBfCwZKbEPFM1YHGP+hqtIqCM
Tc1hAgMBAAGjZjBkMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/BAQDAgEG
MB0GA1UdDgQWBBRtVt7/ADodDpjx4EcpzMBLaQnEnjAfBgNVHSMEGDAWgBRwaTj9
SzoeVTjETP0bt8JifutxzDAKBggqhkjOPQQDAgNIADBFAiAVCdtUTMm6K47k2o70
wNWncKDwp0TuxKDJJ8Tu/0sv0AIhAOSMT2GP70pEKpDnGhmKPUhmkJklDRymewX0
/+wjY4GC
-----END CERTIFICATE-----
"""

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDr7rtBKtpKDyUd
YtIckSKZ/Kt0IiNnRTIrrdP6q8vZ7l89OZhxounWNmQsTtF8CAVz9HLGQrO8d9NC
ebQHyfMtdjFgMI5ePiFugG6SXJvLog67wk4Qz8hxsBS2GDVQP491eBq7+PzheoE5
NgwFIwmE41eymAOncWCM0pBH9T+yl+eHstDE3DXQPWS5TEsykfmw6N9FB8erPBRa
eUrJW/9konTMq4KgzG6k5agzFEWgVNm402HlvfeUfyGlskbNlPMqTHEPGc0zfFRz
f+Ag2YFL3al2mnTXF8/wChiKlTLddL66TFLSYG4vE7Sy7vorNKS0Fenin72kPGEx
XJj7F48dAgMBAAECggEACW2p6AnJXWpLhmgbk26tXk/9ng97MLZQMfSpYvwYkmX3
QmAZ2nizNY9I44hm0LkVVrPvHkMuIZr8Q0zPx/vnDusJQBnQpq1+8oaJZKn0w+d/
BTvXmM5k6T4rJbfD8agImJ4rG1Xw7SXTIjEpu87Ro5DeQVHX24opXJdRkr6XRBDA
WGHtIInj7bbO6uoFRuLcD0vkpZ7ecjp1b5MAj17Qg102DIW7f8G64AG6bwJCdfGi
54bVD098FYtD6ALLeu1jleRIADFrppLApamy99dBZs1XUKFe1IexuCNkgjpnDL/E
h9PfpDIwZ1ZO9YQvNSzwAAH4zNeymEJZHQBUkdWWdQKBgQD2YW/0xfoy2EFscjhC
ZEgsGBmXCXaF4oGag032dYaVVwj7MqmnDKS2pBVn6T/gYLfU5EC0Yd4KOSiSQslw
+yv9P2fwn6tuszKMyhrQ7RV2A01vU02yIYnMIDOzKWZ25HBIvfgcdyxDZgxS1t17
/5a819taZIRZCu9swib1iWCUFwKBgQD1JN29KOmXGCs3viPy0mFdkDZpOJWmKTbX
3sAvcLrvp/gm1fKbaKKffo4hhhJrSfcPE/BcLOyYgmciE/V+j5BNeLyhn3tJfG/I
NSOz2oAvDaWfTx8RTsVpx1KRyz859D7i6mbWEYTZBGO5dVJsimrdTxWhfwkrUruR
euVVCOoS6wKBgG452WSgzfbBWUOzNgg95SwU/B3eVfBADcuawt5oZfWaIqJ/X/ck
aOxtLEZ4y+MOYjAUjf4larkYKVaGGqk5Nczu+Qll5cR41zy1jpm598f8YkBT/Iad
CpEQNxEIjJbUTIe+tanGhz8AALNu/VfkWQPTbodaQPu1MLhvhA6Fj3exAoGAE591
2HRz7lJS801XF1Lb1F9824NaB0j5SOJdw+5kKFbruEAcAXCow9efjPNsegYbrqtL
7DT0Y2jc1I+AcTcQuALYJp/bgJBjakVGrFjrNdkDzvLIa9xAVS1NYLpCP2NbvVJC
FRSl67E8QlYv2NxjnX99HcZLd5pRxV1vChWCly0CgYEA623uuphbqRgzm8cLrGqn
EQ5nnipmptJWiutpa/fiDbOWxc/UcYszjlCluU9Hog+BXzQILMiXtkALhTydzCWy
KH5n/FmPGVAqUBxMgzSek8oL+v4bK8egM5JlX4AI3UVuXkRRT0u+lUopi/afdW/a
AAsUKJed1bWHAdL/tXyLuEg=
-----END PRIVATE KEY-----
"""

[server]
address = "[::0]:50001"

[process]
tracing_level = "INFO"
