[package]
name = "sink_proto"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
doctest = false

[dependencies]
prost = "0"
tonic = "0"

[build-dependencies]
tonic-build = "0"

[package.metadata.cargo-machete]
ignored = ["prost"]
