name: Audits

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./rust

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Install deps
      run: cargo install cargo-audit cargo-deny

    - name: Run cargo-audit 
      run: cargo audit -D warnings

    - name: Run cargo-deny
      run: cargo deny check
