name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./rust

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Protobuf (Unix)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
                V=23.1
                curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${V}/protoc-${V}-${{ runner.os }}-x86_64.zip
                unzip protoc-${V}-${{ runner.os }}-x86_64.zip -d protoc3
                sudo mv protoc3/bin/* /usr/local/bin/
                sudo mv protoc3/include/* /usr/local/include/

      - name: Install Protoc (Windows)
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install protoc --version=23.1

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
  
      - name: Test all the packages
        run: cargo test

